language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t wychme/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wychme/react-test npm run test

after_success:
  - docker build -t wychme/multi-client ./client
  - docker build -t wychme/multi-nginx ./nginx
  - docker build -t wychme/multi-server ./server
  - docker build -t wychme/multi-worker ./worker

deploy: 
  privider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-container-docker"
  env: "multi-container-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-917284451557"
  bucket_path: "MyFirstDocker"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key